# Generated by Django 5.1.15 on 2026-09-11 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('auth_failed', 'Auth failed'), ('error', 'Error')], default='success', max_length=12)),
                ('courses_seen', models.PositiveIntegerField(default=0)),
                ('files_added', models.PositiveIntegerField(default=0)),
                ('files_skipped', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodleCourseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moodle_course_id', models.PositiveIntegerField(unique=True)),
                ('moodle_shortname', models.CharField(blank=True, max_length=255)),
                ('moodle_fullname', models.CharField(blank=True, max_length=255)),
                ('confidence', models.CharField(choices=[('auto', 'Auto-matched'), ('confirmed', 'Confirmed')], default='auto', max_length=10)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moodle_maps', to='academics.course')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moodle_maps', to='academics.courseoffering')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
