# Generated by Django 5.1.15 on 2026-09-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, help_text='Prof./Dr./Eng.', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('degree_level', models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='bachelor', max_length=20)),
                ('partner_institution', models.CharField(blank=True, help_text='e.g. PSUT, THWS for joint programs.', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Normalized, e.g. CS116', max_length=20, unique=True)),
                ('display_code', models.CharField(blank=True, help_text="e.g. 'CS 116'", max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('credit_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='100/200/300 tier', null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('corequisites', models.ManyToManyField(blank=True, related_name='corequisite_of', to='academics.course')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_by', to='academics.course')),
                ('majors', models.ManyToManyField(blank=True, related_name='courses', to='academics.major')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_number', models.CharField(blank=True, max_length=10)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, choices=[('english', 'English'), ('arabic', 'Arabic'), ('german', 'German')], max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('moodle_course_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course')),
                ('instructors', models.ManyToManyField(blank=True, related_name='offerings', to='academics.instructor')),
            ],
            options={
                'ordering': ['-term__year', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz')], max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.courseoffering')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial')], default='lecture', max_length=10)),
                ('day_of_week', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_times', to='academics.courseoffering')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('summer', 'Summer')], max_length=10)),
                ('year', models.PositiveIntegerField(help_text='Academic year the term starts, e.g. 2025')),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-season'],
                'constraints': [models.UniqueConstraint(fields=('season', 'year'), name='uniq_term')],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.term'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'term', 'section_number'), name='uniq_offering'),
        ),
    ]
