# Generated by Django 5.1.15 on 2026-09-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_meetingtime_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_university_wide', models.BooleanField(default=False, help_text='Offered across majors rather than belonging to one.')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='code_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.subject'),
        ),
        migrations.CreateModel(
            name='SubjectPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(max_length=12, unique=True)),
                ('majors', models.ManyToManyField(blank=True, related_name='prefixes', to='academics.major')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='academics.subject')),
            ],
            options={
                'verbose_name_plural': 'subject prefixes',
                'ordering': ['prefix'],
            },
        ),
    ]
