# Generated by Django 5.1.15 on 2026-09-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_course_code_prefix_course_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('university', 'University requirement'), ('school', 'School requirement'), ('program', 'Program requirement'), ('remedial', 'Remedial')], max_length=12)),
                ('requirement', models.CharField(choices=[('compulsory', 'Compulsory'), ('elective', 'Elective')], max_length=12)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('track', models.CharField(blank=True, max_length=120)),
                ('plan_year', models.CharField(blank=True, max_length=20)),
                ('confident', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='academics.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_courses', to='academics.major')),
            ],
            options={
                'ordering': ['major', 'category', 'course'],
                'indexes': [models.Index(fields=['major', 'requirement'], name='academics_p_major_i_3531ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('major', 'course', 'track'), name='uniq_plan_course')],
            },
        ),
    ]
